import { ShieldAlert } from "lucide-react";
import type { Alert } from "../types/domain";
import { Badge, Card, riskBg } from "../components/ui";
import { Section } from "./DashboardPage";

export function DetectionPage({ alerts, statusFilter, setStatusFilter, openAlert, updateStatus }: any) {
  const visible = alerts.filter((alert: Alert) => {
    if (statusFilter === "all") return true;
    if (statusFilter === "critical") return alert.risk_score >= 85;
    if (statusFilter === "ai") return alert.detection_method === "ai";
    return alert.status === statusFilter;
  });

  return <div className="space-y-5"><Section title="Detection Center" description="SOC work queue generated by backend detection engine." icon={<ShieldAlert size={20} />} />
    <div className="grid grid-cols-1 gap-4 md:grid-cols-4">{[["New", alerts.filter((a: Alert) => a.status === "new").length, "text-red-300"], ["In Progress", alerts.filter((a: Alert) => a.status === "in_progress").length, "text-blue-300"], ["Resolved", alerts.filter((a: Alert) => a.status === "resolved").length, "text-emerald-300"], ["Critical", alerts.filter((a: Alert) => a.risk_score >= 85).length, "text-orange-300"]].map(([label, value, color]) => <Card key={label as string} className="p-4"><div className="text-xs text-slate-500">{label}</div><div className={`mt-1 text-3xl font-semibold ${color}`}>{value as any}</div></Card>)}</div>
    <Card className="p-5"><div className="mb-4 flex flex-wrap items-center gap-2">{["all", "new", "in_progress", "resolved", "critical", "ai"].map(filter => <button key={filter} onClick={() => setStatusFilter(filter)} className={`rounded-xl border px-3 py-2 text-xs font-medium capitalize ${statusFilter === filter ? "border-blue-500/40 bg-blue-500/15 text-blue-200" : "border-slate-800 bg-slate-900 text-slate-400 hover:text-slate-100"}`}>{filter.replace("_", " ")}</button>)}</div>
      <div className="space-y-3">{visible.map((alert: Alert) => <div key={alert.alert_id} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><button onClick={() => openAlert(alert)} className="min-w-0 flex-1 text-left"><div className="mb-2 flex flex-wrap items-center gap-2"><Badge className={riskBg(alert.risk_score)}>Risk {alert.risk_score}</Badge><Badge className="border-blue-500/30 bg-blue-500/10 text-blue-200">{alert.status.replace("_", " ")}</Badge><Badge className="border-sky-500/30 bg-sky-500/10 text-sky-200">Rule: {alert.rule_name}</Badge></div><div className="font-medium text-slate-100">{alert.user_id}</div><div className="mt-1 text-sm text-slate-400">{alert.summary}</div><div className="mt-2 font-mono text-xs text-slate-600">{alert.detected_at}</div></button><div className="flex flex-wrap items-center gap-2"><button onClick={() => openAlert(alert)} className="rounded-xl border border-blue-500/30 bg-blue-500/10 px-3 py-2 text-xs font-medium text-blue-200 hover:bg-blue-500/20">Open Detail</button><button onClick={() => updateStatus(alert.alert_id, "in_progress")} className="rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-xs text-slate-300 hover:text-white">In Progress</button><button onClick={() => updateStatus(alert.alert_id, "resolved")} className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 px-3 py-2 text-xs text-emerald-200 hover:bg-emerald-500/20">Resolve</button></div></div></div>)}</div>
    </Card></div>;
}
