import { Database, GitBranch, Lock, ServerCog, User, Zap } from "lucide-react";
import type { AttackGraph, NormalizedEvent } from "../types/domain";
import { Badge, Card, riskBg, riskHex } from "../components/ui";
import { Section } from "./DashboardPage";

export function ReconstructionPage({ graph, openEvent, events }: { graph: AttackGraph | null; openEvent: (event: NormalizedEvent) => void; events: NormalizedEvent[] }) {
  if (!graph) return <Card className="p-8 text-slate-400">Loading attack graph...</Card>;
  const positioned = graph.nodes.map((n, i) => ({ ...n, x: 110 + (i % 4) * 210, y: i % 2 === 0 ? 130 : 250 }));
  const pos = Object.fromEntries(positioned.map(n => [n.id, n]));
  return <div className="space-y-5"><Section title="Attack Reconstruction" description="Backend-generated node/edge graph from related CloudTrail events." icon={<GitBranch size={20} />} />
    <div className="grid grid-cols-1 gap-5 2xl:grid-cols-[1fr_380px]"><Card className="overflow-hidden p-5"><div className="mb-4 flex items-center justify-between"><div><div className="text-sm font-medium text-slate-100">API Call Relationship Graph</div><div className="text-xs text-slate-500">Nodes are identities/resources. Edges are API calls.</div></div><Badge className="border-red-500/30 bg-red-500/10 text-red-200">{graph.edges.length} edges</Badge></div><div className="relative h-[370px] overflow-hidden rounded-2xl border border-slate-800 bg-slate-950"><svg viewBox="0 0 850 360" className="h-full w-full"><defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L0,6 L9,3 z" fill="#475569" /></marker></defs>{graph.edges.map(edge => { const s = pos[edge.source]; const t = pos[edge.target]; const event = events.find(e => e.eventID === edge.event_id); if (!s || !t) return null; return <g key={edge.event_id} onClick={() => event && openEvent(event)} className="cursor-pointer"><line x1={s.x} y1={s.y} x2={t.x} y2={t.y} stroke={edge.risk === "critical" ? "#ff4d4f" : edge.risk === "high" ? "#faad14" : "#1890ff"} strokeWidth="2.5" markerEnd="url(#arrow)" /><rect x={(s.x + t.x) / 2 - 44} y={(s.y + t.y) / 2 - 13} width="88" height="24" rx="8" fill="#020617" stroke="#1e293b" /><text x={(s.x + t.x) / 2} y={(s.y + t.y) / 2 + 4} fill="#cbd5e1" fontSize="11" textAnchor="middle">{edge.action}</text></g>; })}{positioned.map(node => { const Icon = node.type === "user" ? User : node.type === "s3" ? Database : node.type === "ec2" ? ServerCog : Lock; return <g key={node.id}><circle cx={node.x} cy={node.y} r={node.risk_score >= 90 ? 36 : 31} fill="#020617" stroke={riskHex(node.risk_score)} strokeWidth="2.5" /><foreignObject x={node.x - 14} y={node.y - 14} width="28" height="28"><Icon size={24} color={riskHex(node.risk_score)} /></foreignObject><text x={node.x} y={node.y + 52} fill="#e2e8f0" fontSize="12" textAnchor="middle">{node.label}</text><text x={node.x} y={node.y + 68} fill="#64748b" fontSize="10" textAnchor="middle">risk {node.risk_score}</text></g>; })}</svg></div></Card>
      <Card className="p-5"><div className="mb-4 flex items-center gap-2 text-sm font-medium text-slate-100"><Zap size={16} /> Kill Chain</div><div className="space-y-4">{graph.kill_chain.map((step, idx) => <div key={`${step.stage}-${idx}`} className="relative flex gap-3"><div className="flex flex-col items-center"><div className={`flex h-8 w-8 items-center justify-center rounded-full border ${riskBg(step.risk === "critical" ? 95 : step.risk === "high" ? 75 : 45)}`}>{idx + 1}</div>{idx < graph.kill_chain.length - 1 && <div className="h-12 w-px bg-slate-800" />}</div><div className="pb-2"><div className="font-medium text-slate-100">{step.stage}</div><div className="mt-1 text-xs text-slate-500">{step.timestamp.slice(11, 16)}</div><div className="mt-1 text-sm text-slate-400">{step.description}</div></div></div>)}</div></Card></div>
  </div>;
}
