import { Clock } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { TimelineEvent } from "../types/domain";
import { Badge, Card, riskBg } from "../components/ui";
import { Section } from "./DashboardPage";

export function TimelinePage({ userId, timeline, setPage }: { userId: string; timeline: TimelineEvent[]; setPage: (page: string) => void }) {
  return <div className="space-y-5"><Section title="User Behavior Timeline" description={`Behavior sequence for ${userId}.`} icon={<Clock size={20} />} action={<button onClick={() => setPage("reconstruction")} className="rounded-xl border border-blue-500/30 bg-blue-500/10 px-4 py-2 text-sm font-medium text-blue-200 hover:bg-blue-500/20">View Graph</button>} />
    <Card className="p-5"><div className="mb-4 flex items-center justify-between"><div><div className="text-sm font-medium text-slate-100">Interactive Risk Timeline</div><div className="text-xs text-slate-500">Built by backend timeline_builder.</div></div><Badge className="border-red-500/30 bg-red-500/10 text-red-200">{timeline.filter(t => t.is_anomaly).length} anomalies</Badge></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={timeline}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b" /><XAxis dataKey="time" stroke="#64748b" fontSize={12} /><YAxis stroke="#64748b" fontSize={12} domain={[0, 100]} /><Tooltip contentStyle={{ background: "#020617", border: "1px solid #1e293b", borderRadius: 12, color: "#e2e8f0" }} /><Line type="monotone" dataKey="risk_score" stroke="#1890ff" strokeWidth={3} /></LineChart></ResponsiveContainer></div></Card>
    <Card className="p-5"><div className="mb-4 text-sm font-medium text-slate-100">Action Sequence</div><div className="space-y-3">{timeline.map((item, idx) => <div key={item.id} className="flex w-full items-center gap-4 rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className={`flex h-10 w-10 items-center justify-center rounded-full border ${item.is_anomaly ? "border-red-500/40 bg-red-500/10 text-red-200" : "border-blue-500/35 bg-blue-500/10 text-blue-200"}`}>{idx + 1}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-medium text-slate-100">{item.event_name}</span><Badge className={riskBg(item.risk_score)}>{item.risk_score}</Badge>{item.is_anomaly && <Badge className="border-red-500/30 bg-red-500/10 text-red-200">Anomaly</Badge>}</div><div className="mt-1 text-xs text-slate-500">{item.time} · {item.stage} · {item.status}</div></div></div>)}</div></Card>
  </div>;
}
